version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        TARGET: ${TARGET:-development}
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend/data:/app/data
    image: daveandrew/machine-learning-frontend:latest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend/data:/app/data
    image: daveandrew/machine-learning-backend:latest