# CI/CD pipeline
name: Flask & Next.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: |
          cd frontend
          npm install
        
      - name: Build and Test Next.js Frontend
        run: |
          cd frontend
          npm run build

      - name: Build and Run Docker Containers
        run: |
          export TARGET=production
          docker-compose up -d

  docker_build:
    runs-on: ubuntu-latest
    name: Docker Image Build
    needs: build-and-deploy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker-compose build
          docker-compose push

  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment to Private VPS
    needs: docker_build
    steps:
    - name: Deploy to Private VPS using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          mkdir /${{secrets.USERNAME}}/machine-learning-aol
          cd /${{secrets.USERNAME}}/machine-learning-aol
          wget -O docker-composer.server.yaml https://raw.githubusercontent.com/MachineLearningDrugConsumptionProject/website-machine-learning-drug-consumption/main/docker-composer.server.yaml
          docker-compose -f docker-compose.server.yaml down
          docker-compose -f docker-compose.server.yaml pull
          docker-compose -f docker-compose.server.yaml up -d

